module.exports = {

halo5_default: {
  "start": "pause",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "melee",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "crouch",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "dodge",
  "left-d-pad":"switch grenades left",
  "right-d-pad":"switch grenades right",
  "up-d-pad": "issue orders",
  "down-d-pad": "tracking"
},

halo5_green_thumb: {
  "start": "pause",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "dodge",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"switch grenades left",
  "right-d-pad":"switch grenades right",
  "up-d-pad": "issue orders",
  "down-d-pad": "tracking"
},

halo5_recon: {
  "start": "pause",
  "select": "scoreboard",
  "left-bumper": "dodge",
  "left-trigger": "throw grenade",
  "right-trigger": "fire weapon",
  "right-bumper": "reload",
  "left-thumbstick-toggle":"crouch",
  "right-thumbstick-toggle": "zoom",
  "A": "jump",
  "X": "sprint",
  "Y": "switch-weapon",
  "B": "melee",
  "left-d-pad":"switch grenades left",
  "right-d-pad":"switch grenades right",
  "up-d-pad": "issue orders",
  "down-d-pad": "tracking"
},

halo5_fish_stick: {
  "start": "pause",
  "select": "scoreboard",
  "left-bumper": "dodge",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"switch grenades left",
  "right-d-pad":"switch grenades right",
  "up-d-pad": "issue orders",
  "down-d-pad": "tracking"
},

halo5_halo4: {
  "start": "pause",
  "select": "scoreboard",
  "left-bumper": "dodge",
  "left-trigger": "throw grenade",
  "right-trigger": "fire weapon",
  "right-bumper": "melee",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "zoom",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"switch grenades left",
  "right-d-pad":"switch grenades right",
  "up-d-pad": "issue orders",
  "down-d-pad": "tracking"
},

halo5_boxer: {
  "start": "pause",
  "select": "scoreboard",
  "left-bumper": "dodge",
  "left-trigger": "melee",
  "right-trigger": "fire weapon",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"crouch",
  "right-thumbstick-toggle": "zoom",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "sprint",
  "left-d-pad":"switch grenades left",
  "right-d-pad":"switch grenades right",
  "up-d-pad": "issue orders",
  "down-d-pad": "tracking"
},

halo5_southpaw: {
  "start": "pause",
  "select": "scoreboard",
  "left-bumper": "melee",
  "left-trigger": "fire weapon",
  "right-trigger": "throw grenade",
  "right-bumper": "dodge",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "zoom",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"switch grenades left",
  "right-d-pad":"switch grenades right",
  "up-d-pad": "issue orders",
  "down-d-pad": "tracking"
},

halo5_bumperjumper: {
  "start": "pause",
  "select": "scoreboard",
  "left-bumper": "jump",
  "left-trigger": "throw grenade",
  "right-trigger": "fire weapon",
  "right-bumper": "melee",
  "left-thumbstick-toggle":"crouch",
  "right-thumbstick-toggle": "zoom",
  "A": "sprint",
  "X": "dodge",
  "Y": "switch-weapon",
  "B": "reload",
  "left-d-pad":"switch grenades left",
  "right-d-pad":"switch grenades right",
  "up-d-pad": "issue orders",
  "down-d-pad": "tracking"
},

callofduty_default: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "lethal equipment",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},

callofduty_tatical: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "lethal equipment",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "crouch",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "melee",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},
callofduty_lefty: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "lethal equipment",
  "left-trigger": "fire weapon",
  "right-trigger": "zoom",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"melee",
  "right-thumbstick-toggle": "sprint",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},
callofduty_NOM4D: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "lethal equipment",
  "right-trigger": "fire weapon",
  "right-bumper": "zoom",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},
callofduty_NOM4D_tactical: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "lethal equipment",
  "right-trigger": "fire weapon",
  "right-bumper": "zoom",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "crouch",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "melee",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},
callofduty_NOM4D_l3f7y: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "zoom",
  "left-trigger": "fire weapon",
  "right-trigger": "lethal equipment",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},

callofduty_bumper_jumper: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "jump",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "lethal equipment",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "throw grenade",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},

callofduty_bumper_jumper_tactical: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "jump",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "lethal equipment",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "crouch",
  "A": "throw grenade",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "melee",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},

callofduty_charlie: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "lethal equipment",
  "right-trigger": "fire weapon",
  "right-bumper": "zoom",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},

callofduty_one_hand_gunslinger: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "fire weapon",
  "left-trigger": "zoom",
  "right-trigger": "lethal equipment",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},

callofduty_stick_and_move: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "lethal equipment",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "jump",
  "A": "melee",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},

callofduty_scout: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "lethal equipment",
  "left-thumbstick-toggle":"melee",
  "right-thumbstick-toggle": "reload",
  "A": "jump",
  "X": "crouch",
  "Y": "switch-weapon",
  "B": "sprint",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},

callofduty_brawler: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "melee",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "lethal equipment",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},


callofduty_beast: {

  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "jump",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "melee",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "lethal equipment",
  "A": "throw grenade",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"divison skill",
  "right-d-pad":"activate scorestreak",
  "up-d-pad": "scorestreak up",
  "down-d-pad": "scorestreak down"
},

destiny2_Jumper: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "jump",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "super ability",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"custom",
  "right-d-pad":"dance",
  "up-d-pad": "wave",
  "down-d-pad": "sit"
},

battlefield4_default: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "spot",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"gadget",
  "right-d-pad":"gadget",
  "up-d-pad": "accessory",
  "down-d-pad": "fire mode"
},

battlefield4_veteran: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "spot",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "crouch",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "melee",
  "left-d-pad":"gadget",
  "right-d-pad":"gadget",
  "up-d-pad": "accessory",
  "down-d-pad": "fire mode"
},

battlefield4_lefty: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "spot",
  "left-trigger": "fire weapon",
  "right-trigger": "zoom",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"gadget",
  "right-d-pad":"gadget",
  "up-d-pad": "accessory",
  "down-d-pad": "fire mode"
},

battlefield4_lefty_veteran: {
  "start": "menu",
  "select": "scoreboard",
  "left-bumper": "spot",
  "left-trigger": "fire weapon",
  "right-trigger": "zoom",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "crouch",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "melee",
  "left-d-pad":"gadget",
  "right-d-pad":"gadget",
  "up-d-pad": "accessory",
  "down-d-pad": "fire mode"
},

battlefield1_default: {
  "start": "menu",
  "select": "full map",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "spot",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"gadget",
  "right-d-pad":"gadget",
  "up-d-pad": "gas mask",
  "down-d-pad": "fire mode"
},

battlefield1_alternate: {
  "start": "menu",
  "select": "full map",
  "left-bumper": "throw grenade",
  "left-trigger": "zoom",
  "right-trigger": "fire weapon",
  "right-bumper": "spot",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "crouch",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "melee",
  "left-d-pad":"gadget",
  "right-d-pad":"gadget",
  "up-d-pad": "gas mask",
  "down-d-pad": "fire mode"
},

battlefield1_lefty: {
  "start": "menu",
  "select": "full map",
  "left-bumper": "spot",
  "left-trigger": "fire weapon",
  "right-trigger": "zoom",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "melee",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "crouch",
  "left-d-pad":"gadget",
  "right-d-pad":"gadget",
  "up-d-pad": "gas mask",
  "down-d-pad": "fire mode"
},

battlefield1_lefty_alternate: {
  "start": "menu",
  "select": "full map",
  "left-bumper": "spot",
  "left-trigger": "fire weapon",
  "right-trigger": "zoom",
  "right-bumper": "throw grenade",
  "left-thumbstick-toggle":"sprint",
  "right-thumbstick-toggle": "crouch",
  "A": "jump",
  "X": "reload",
  "Y": "switch-weapon",
  "B": "melee",
  "left-d-pad":"gadget",
  "right-d-pad":"gadget",
  "up-d-pad": "gas mask",
  "down-d-pad": "fire mode"
}

}
